### ISSUE TITLE
Weird Error, how do I fix this

### ISSUE THREAD

**Issue by Nonethousand** [PeachyPeachSM64/sm64ex-omm#6] opened 2022-09-17 01:55 UTC
This is my error: 
```
$ python3 omm_builder.py
--- Checking OMM version...
Unable to retrieve remote OMM version number.
Using local OMM patch...
<!> ERROR: Cannot find any OMM patch.
```

However, I did not change any of the files. The omm patch is still there, everything. My internet is working, so it should be able to get the version. I even looked through the .py file to see if I could find out what was going wrong.  Another weird thing, it was working before. There was a part of the readme that said something about having to reinstall MSYS2 because of the python asset extraction error, but from what I see it is not extracting anything. How do I fix this?

**Comment by miqumi** [comment] 2022-09-23 11:59
try reinstalling the builder

**Comment by Nonethousand** [comment] 2022-09-23 16:03
> try reinstalling the builder

I did that, like 5 times and it still doesn't work.

**Comment by PeachyPeachSM64** [comment] 2022-12-06 00:51
Cannot reproduce that issue. Closing it.

**Closed as completed by PeachyPeachSM64** 2022-12-06 00:51 UTC
